### ISSUE TITLE
Does it make sense to reset the legend every time a new point is clicked?

### ISSUE THREAD

**Issue by aazaff** [UW-Macrostrat/web#32]
This is a UX question that has no "right" answer.

Let's say I am interested in perusing the primary literature of formations in an area by examining the **Primary Literature via GeoDeepDive** pane.  So I minimize all of the top panes and expand the primary lit pane. If I click a new point, everything will reset to the previous point and I must again minimize all the to panes and expand the primary pane. 

Is this the optimum behaviour?

**Comment by davenquinn** [comment]
I'm taking a look at the web codebase now. You are absolutely correct that this "capturing" of the map position is not great UX, because it significantly curtails the ability to explore around naturally with the panel open.

To do this better, we will need to have a more nuanced idea of when the user means to view a new position. One possibility: dragging keeps the same position selected but moves the map; clicking sets a new position. The panel state would stay the same although the content would change. I think this may be the simplest.

**Comment by aazaff** [comment]
I concur with the diagnosis and with the prescription.

**Comment by davenquinn** [comment]
This is now very much the way it works.
