### ISSUE TITLE
Massive CPU load when zooming or panning

### ISSUE THREAD

**Issue by mrtnlowry** [UW-Macrostrat/web#77]
iNaturalist.org recently added a link to the service. Accessing the link loads the page fine but zooming or panning the map pushes my 3.4GHz quad core i7 to maximum.
Running in Chrome [Version 109.0.5414.120 (Official Build) (64-bit)] on Windows 10.

**Comment by davenquinn** [comment]
I have looked into this and found a few small performance optimizations and bug fixes, but nothing that would cause that level of performance hit. Most of this is likely due to the data intensity and graphical complexity of the map display. It is also quite CPU-intensive when moving the map on my machine.

There are several features of MapboxGL that we are using for graphical quality (e.g., antialiasing, high-resolution hillshades) that we could turn off to improve the map's performance. We will consider exposing a setting to pin these to less intensive values if desired.

**Comment by mrtnlowry** [comment]
Hello David,

Many thanks for reply so promptly.

I have discovered perhaps the major cause of the issue. I had forgotten
that I had turned off hardware acceleration in Chrome (several updates ago
it was causing Chrome to crash and turning it off resolved that problem).
Now that I have turned it back on CPU load has decreased to about 50% on
pan and zoom. Acceptable I guess. Maybe your solution should be to check
the hardware acceleration status on first use and warn the user rather than
adding extra settings.

Even with HA now on I find that the page quickly stops rendering when I try
to scroll through the panels under 'Usage'. Each panel turns black and the
main page map disappears. Reloading the page restores the main map but I
lose my place in the "Usage" list. Perhaps my old GPU (AMD Radeon 9 200)
isn't really man enough for the task.

I suggest we mark the issue as closed on GitHub.

Regards,
Martin
